name: AWS NOC CICD Github Action
on:
   push:
    branches: 
      - main
jobs:
  build:
    environment: 'prod'
    runs-on: ubuntu-latest
    steps:
      - name: Terraform plan
        run: | 
          echo "terraform plan"
      - name: Terraform apply
        run: |
          echo "terraform apply"
